version: '3.1'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - dynamodb-network
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  dynamo-admin:
    build: ./local-env/dynamo-admin/
    container_name: dynamo_admin_acid
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=eu-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - "8001:8001"
    networks:
      - dynamodb-network
networks:
  dynamodb-network:
    driver: bridge