version: '3.1'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  dynamo-admin:
    build: ./local-env/dynamo-admin/
    container_name: dynamo_admin_dhvs
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "8001:8001"
